AWSTemplateFormatVersion: 2010-09-09
Resources:
  Route53Zone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: "example zone"
      Name: "me.example.com"